spring:
  application:    name: GatewayAPI
    
server:  port: 8080
  
eureka: 
  client: 
    service-url: 
      default-zone: ${EUREKA_URI:https://localhost:8761/eureka}
  instance: 
    prefer-ip-address: true

zuul:  ignored-services: '*'
  prefix: /api
  routes:    category-service:
      path: /category/**
      service-id: CategoryAPI
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
    company-service:
      path: /company/**
      service-id: CompanyAPI
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
    account-service:
      path: /account/**
      service-id: AccountAPI
      sensitiveHeaders: Cookie,Set-Cookie,Authorization

  host:    socket-timeout-millis: 30000
